language: python
python:
- '2.7'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- coverage run --source=pylj setup.py test
- coveralls
deploy:
  provider: pypi
  user: arm61
  password:
    secure: Yh86mU6cvLkzfe8ytEgDyYLVuunodijqFO8DKrjK2ZcAEACv3Yxu1egx/8yenzt10WTnldlBMxYYznxOqz3SD+qrc/IBRiWRlfVxVxd7SoBg2R8PyW76MFP1eVJ2c9Xz5cXyhTRmmzC2brzMiglrZ8aOAbyBrXzc855rXz+CSDNOPhYB4BMhEJxLa8oX97F0OTrm/p8vXNminXKwyQaoH+mX5qJy7k/naIaQIIZAb6fqow1dqyhlYQnNi6wFwOnTHsJwiPWuEYnWqv0KQFPSi4qstzmlq3FM4Sv9TjrRILZuqo/xasc9pN3Ni/Wh2fmdduQGWJG0CukyJ4XbF8pYc9S8D3dv29UFMLk0bSGVc2A+fB5211UTujl65mLiQz0BxPZ1VaO5UU1x5m2mGkiGoU99NWrzx0krcPhgP00qG3X7pDN70qsIt1ppdzv2p4ZstnMs1wQhEfBmdwrQdKG6+N/god6N47686j0LZXFkzn26fjzqBujgI00kYW72QwcnkRcOFZy/l3B83IVQtNpF9ucoEze9OJ87IlDY6eNV9d5dXesc49eD3pGrwmpejajT438Iaa+FDI/vgSArq/2Jiz0ZqhY0Z/A7EAmoj3/j5Lee+VmijCHesh7U0bVZcj2orOUjOK23IQZx4k+Zt0ibqV4AkpE3TZfp/s/ZBRMsJac=
  on:
    distributions: sdist
    python: '3.6'
    branch: master
    repo: arm61/pylj
