language: python
python:
- '2.7'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- coverage run --source=pylj setup.py test
- coveralls
deploy:
  provider: pypi
  user: arm61
  password:
    secure: lq27o871XbMNjYaAnY+XjPD3bQFbk9wCITvege7OQvCyGka6iWG3xcgtozKnWiZk/tsro3FZUvRvWlbwueT/1dm+0Hk4NNWDqqUpl7VMe2R86fXh6ZHhGrPwy3cR4ptKSKlDeGR1tBq0LCEgfeMXepX2KCnZtl/J9sUqTxIValZb+sdHUt51JXhtZrr0qKfVfw0yr9ixi7VDWTLhHfaxyRU5o+I+lJnX/MHY5RKDUZffglz79sKth7LYYRcc8SAc8dTmN4DIZfz+oMFMzr3WRalMpj2YN92HY3HLQKy3QTu8nokk0C226DIb3RKCZJf7TNMA7YxWfDGgzF0ac1DS0t2I2+ILHJ+oJ+l/sK+/bFeXqaxsuq+b30hprt5B8SV7bCfFa7evsokUY1eo5iOiYmxTjxBsGHwGdgij9ThdejBKcir6OXe5DvXZpgIn27FKApto8rtDiKWA2zVPVuZl8JJtJuOLovxGe7O07udTE43Db1EQWgotOKJu5XnJkuJGwXoRQDHIvc5txThmGO6ld350QOzER5BM22VRrggsnZ2zbszl5XuzrKtfVZUSOrAHUqfKw+mFzR++FVwNC3hGamnTmu6TYOgzgDsoor/LIBABxpgLHLykuJ2lbqrGCnGN0j0KfgH0WUiOYET6POgr5vbhm3K3+W7Yl3p5Yw8xebc=
  on:
    distributions: sdist
    python: '3.6'
    branch: master
    repo: arm61/pylj
