language: python
python:
  - '2.7'
  - '3.5'
  - '3.5-dev'
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=pylj setup.py test
  - coveralls
deploy:
  provider: pypi
  user: arm61
  password:
    secure: GR854z6f1+6GPESZHPmeLZS3uESPTSuuFMGDGTjtVo7yG8sk+6eyRj1pgTz477YCuzBpUM05zy7GHgve71umOYLkBcqXYXtzM8chbvsMnC+nVNzNa5XP32Owlr8B9qCcLvRzhGCQORz3yP6cm8uxUnrF0FsqNwdvWc60MiF9sB+YNFIEehSRF8VazdMlr+SM8TCnUJES67nThJ3II0y6NgPc+Tz/dwAel5eNXWbWCvFTcJAAXWcCo0U1y6XOUDw+sY5rCjbiwjwtRBZheNfp/HdHN3HyFJIoTZ4dn50CJaAaxT+8mKe35osTJyqWOTjXEedr1feHe+Ly3nfiqSXvi3SbWP/czjHH88TQ6ECfNlTUjg0uUinprYJpjaEiyoLI+cbCaeIFe9GjnqIT8ZWc7dJ1+8/N7xteJEdFmFHQ+yJwUwQ+BvOPNUPE9SbiKMLC/Tv7r8xk4z8MljPwQWFYTL9/ThaZTAkJVXBqpWRmzJYdGVOcZAwS84OOrku0Q289+Xi/NyDOqOGasfYVBhKk4hIrglh1+aYSZlumh7n+mpVnjcKHcwZp9opI75u0Udmga1uf7T8V/yjHyD8pe+30+qCN7V9sqpD2X5+HieTt4zdieWykrbQbdkiqrRdgjxpp8WYH8LpGglHyrDHW+9c2EwhSnG/DzL3dN3a30OhnBQ=
  on:
    distributions: sdist
    python: '3.6'
    branch: master
    repo: arm61/pylj
