language: python
python:
- '2.7'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- coverage run --source=pylj setup.py test
- coveralls
deploy:
  provider: pypi
  user: arm61
  password:
    secure: X3BkFt+QraYCwx0zGsRzUEFeuiUQNOIfR7cTZ0Es0HK1qnXEz6CkIPwoTnkUZoWHi8wc9xp95/5L+7uMcZGlv62xASN7F8NX1XGqwVrohYU9Agam2KhERpjcleJWzRONdrXJyAC3QS67vU/ylwjCpYrP2ktsSVavrOy2pPDTKaN3eVwzznIEM6ebOFp3F41qEjui/BEoLqltu5cKaUTdIxB6H8LMtqthwlUHTEoPcjaHsYBDx+rTlzg5fh91jQ85J5/oKn4ohqg47c67vOkMkbtTkQDpA6nIFKxW8+hwKbhKEo8L4VHn3MgVDiSllahjcfeFuYiCFLSbZIuyEi6ozzXegvseR1A83jKBspnlgjKfaWsm1joxEavde6ds5W+qc208QTguvWaofQvH1tIidZFkXBkcdOw1HUcGOHB3iCTy30fIbz/l9YXkv/DZGYMVXBwdhqTaXsnIv3dE107fQ1bsrHcIT6OKZsmvDZ5dzHILx38ssa0qch0sLiPqjqP9A8N/i3GO+Nd4TcX8Mz9gIdRxdaFQwc1rTZYN/Ax/amLulcEsMfChFBUY8JT9aUcCVh9fN6S4DkuYshOHXvSy6eEHlItI4DbTEBveFYc61bgZpZlTkAmoQIKp9hym11xxt2MJGtBOXAy62Caxb+jrqs3cmKDgMV2g08mjUyrxPAA=
  on:
    distributions: sdist
    python: '3.6'
    branch: master
    repo: arm61/pylj
