language: python
os:
  - linux
  - osx
python:
  - '2.7'
  - '3.5'
  - 3.5-dev
  - '3.6'
  - 3.6-dev
  - 3.7-dev
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=pylj setup.py test
  - coveralls
deploy:
  provider: pypi
  user: arm61
  password:
    secure: XSInByrtEDLcOHJTBFLz1oNPQRf+5ix8i8nZQKbCr2X9vRPT1GBUwS5SXQuP1QblTd2FB3a9de6V962YhIr+D/yaCrz+SEFa+MSn8in8AFeH2Uq6Y+hsIlQkKNDKf4MtzVglvPmfie4kf81mubdpJmmXUSUkI27DK9SfJFoX7r45TzQcykBTKqnMHIb6fdkhHGmkRQchIbjsu08VoQdguN5v43fm5y0mqPaE3hjZ6snZ4pj83HrMDp5r8reqBfk8suicKKimTmfoCLRG84pDA7xp/k6zKALn/4sLaGH+vVBjhRnvQDoD3+33OG8HebFRyD3gnUYrCkBfLq9Tv7qbP4vMm6cn2n//zTo0Q4jCoSmaJwcu95h3j0GtU3TOgkhwwZrMYp58EmKklRtC9DP2YUbbgHeJdldFG7SbVWBtZaHFoiDd5zpOq34+QvnhGF1YzDAyH7skC/ceZEklbEqSUmuoO5viHLqpnKxix364ZREvR2ZqI5W4mPBbpFh9u5FAiJOfuD6o5zIkTIGnkIhdWDS7OP189ah1iduy9HgAhh4rndgKs7H0xdgtTxKxZ4tT9WT78bqSvJeFC5NOULjf79v4TK0Oijg7OrPFw4/I45q3QIASA66e3LhCYakUq/Fdyhgk6AkrABvcFAkAmSgpVL5dMnDOEdUzpZlDhIYLOeA=
  distributions: "sdist bdist_wheel"
